from datetime import date

d = date(2020, 10, 16)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2020, 10, 30)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2020, 11, 13)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2020, 11, 27)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2020, 12, 11)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2020, 12, 25)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2021, 1, 8)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2021, 1, 22)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2021, 2, 5)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")
d = date(2021, 2, 19)
print(d.year)
print(d.month)
print(d.day)
print(d.strftime("%Y %m %d"))
print("\n")

